// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../../../index.js";

/**
 * @example
 *     {
 *         business: "business",
 *         fulfillment_method: "ship"
 *     }
 */
export interface ChooseFulfillmentMethodRequest {
    /** The business handle */
    business: string;
    fulfillment_method: FiveOneEat.FulfillmentType;
}
