// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         business: "business"
 *     }
 */
export interface ListShippingOptionsCartRequest {
    /** The business handle */
    business: string;
}
