// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         business: "business",
 *         amount: 1
 *     }
 */
export interface RefreshCartPaymentRequest {
    /** The business handle */
    business: string;
    amount: number;
}
