// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         business: "business",
 *         provider_rate_id: "provider_rate_id"
 *     }
 */
export interface SelectShippingRateRequest {
    /** The business handle */
    business: string;
    provider_rate_id: string;
}
