// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         business: "business",
 *         address: {
 *             line1: "line1",
 *             city: "city",
 *             state: "state",
 *             postal_code: "postal_code"
 *         }
 *     }
 */
export interface ShippingAddressRequest {
    /** The business handle */
    business: string;
    address: ShippingAddressRequest.Address;
}

export namespace ShippingAddressRequest {
    export interface Address {
        line1: string;
        line2?: (string | null) | undefined;
        city: string;
        state: string;
        postal_code: string;
        country?: string | undefined;
    }
}
