// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         event: "event"
 *     }
 */
export interface UpdateEventRequest {
    /** The event ID */
    event: string;
    title?: string;
    description?: string | null;
    location?: string | null;
    venue_address?: string | null;
    venue_city?: string | null;
    venue_state?: string | null;
    venue_zipcode?: string | null;
    venue_country?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    starts_at?: string;
    ends_at?: string;
    is_all_day?: boolean;
    is_featured?: boolean;
    ticket_sales_enabled?: boolean;
    is_published?: boolean;
    sort_order?: number | null;
}
