// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../../index.js";

export interface NearbyStandsResponse {
    data: FiveOneEat.NearbyStand[];
    meta: NearbyStandsResponse.Meta;
}

export namespace NearbyStandsResponse {
    export interface Meta {
        arrival_radius_meters: number;
    }
}
