// This file was auto-generated by Fern from our API Definition.

export interface CreatePaymentIntentTicketingResponse {
    status: string;
    client_secret: string;
    payment_intent_id: string;
    subtotal: number;
    tax_amount: number;
    tax_calculation: CreatePaymentIntentTicketingResponse.TaxCalculation | null;
    shipping_amount: number;
    shipping_method: unknown | null;
    platform_fee: number;
    total_amount: number;
    total_cents: number;
    /**
     * The stored intent as it stood before this call, so a caller can
     * tell whether the price the buyer is about to pay just moved.
     */
    previous_payment_intent_id: string | null;
    previous_amount_cents: string | null;
}

export namespace CreatePaymentIntentTicketingResponse {
    export interface TaxCalculation {
        id: string;
        amount_total: number;
        tax_amount_exclusive: number;
    }
}
