// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("CartClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/customer/businesses/business/cart")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.get({
            business: "business",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/business/cart")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.get({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/business/cart")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.get({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("addItem (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { variant_id: "variant_id", quantity: 1 };
        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.addItem({
            business: "business",
            body: {
                variant_id: "variant_id",
                quantity: 1,
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addItem (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { variant_id: "variant_id", quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.addItem({
                business: "business",
                body: {
                    variant_id: "variant_id",
                    quantity: 1,
                },
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("addItem (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { variant_id: "variant_id", quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.addItem({
                business: "business",
                body: {
                    variant_id: "variant_id",
                    quantity: 1,
                },
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("addItem (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { variant_id: "variant_id", quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.addItem({
                business: "business",
                body: {
                    variant_id: "variant_id",
                    quantity: 1,
                },
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("clear (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/customer/businesses/business/cart").respondWith().statusCode(200).build();

        const response = await client.customer.cart.clear({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });

    test("clear (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/businesses/business/cart")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.clear({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("clear (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/businesses/business/cart")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.clear({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("updateItem (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.updateItem({
            cartItem: "cartItem",
            quantity: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateItem (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.updateItem({
                cartItem: "cartItem",
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("updateItem (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.updateItem({
                cartItem: "cartItem",
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("updateItem (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.updateItem({
                cartItem: "cartItem",
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("updateItem (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.updateItem({
                cartItem: "cartItem",
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("removeItem (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .delete("/customer/cart/items/cartItem")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.removeItem({
            cartItem: "cartItem",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeItem (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/cart/items/cartItem")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.removeItem({
                cartItem: "cartItem",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("removeItem (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/cart/items/cartItem")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.removeItem({
                cartItem: "cartItem",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("removeItem (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/cart/items/cartItem")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.removeItem({
                cartItem: "cartItem",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("createPaymentIntent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            client_secret: "client_secret",
            payment_intent_id: "payment_intent_id",
            subtotal: 1.1,
            tax_amount: 1.1,
            shipping_amount: 1.1,
            platform_fee: 1.1,
            total_amount: 1.1,
            amount: 1,
            currency: "usd",
        };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.createPaymentIntent({
            business: "business",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createPaymentIntent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.createPaymentIntent({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("createPaymentIntent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.createPaymentIntent({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("createPaymentIntent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.createPaymentIntent({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.ConflictError);
    });

    test("createPaymentIntent (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.createPaymentIntent({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("refreshPaymentIntent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 1 };
        const rawResponseBody = {
            total_changed: true,
            client_secret: "client_secret",
            payment_intent_id: "payment_intent_id",
            subtotal: 1.1,
            tax_amount: 1.1,
            shipping_amount: 1.1,
            platform_fee: 1.1,
            total_amount: 1.1,
            amount: 1,
            currency: "usd",
        };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent/refresh")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.refreshPaymentIntent({
            business: "business",
            amount: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("refreshPaymentIntent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent/refresh")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.refreshPaymentIntent({
                business: "business",
                amount: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("refreshPaymentIntent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent/refresh")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.refreshPaymentIntent({
                business: "business",
                amount: 1,
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("refreshPaymentIntent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent/refresh")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.refreshPaymentIntent({
                business: "business",
                amount: 1,
            });
        }).rejects.toThrow(FiveOneEat.ConflictError);
    });

    test("refreshPaymentIntent (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amount: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/payment-intent/refresh")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.refreshPaymentIntent({
                business: "business",
                amount: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("checkout (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = {
            data: {
                id: "id",
                order_number: "order_number",
                status: "status",
                fulfillment_status: "fulfillment_status",
                fulfillment_method: "fulfillment_method",
                pickup_date: "pickup_date",
                pickup_time: "pickup_time",
                subtotal_cents: 1,
                discount_cents: 1,
                shipping_cents: 1,
                tax_cents: 1,
                platform_fee_cents: 1,
                total_cents: 1,
                currency: "currency",
                shipping_address: { key: "value" },
                notes: "notes",
                fulfilled_at: "fulfilled_at",
                refunded_at: "refunded_at",
                business: { id: "id", handle: "handle", name: "name" },
                transaction: {
                    ulid: "ulid",
                    status: "status",
                    refunded_amount_cents: 1,
                    refundable_amount_cents: 1,
                    payment_completed_at: "payment_completed_at",
                    refunded_at: "refunded_at",
                },
                tracking_number: "tracking_number",
                tracking_url: "tracking_url",
                shipments: "shipments",
                items: [{ id: "id", variant_id: "variant_id", quantity: 1, unit_price_cents: 1, total_cents: 1 }],
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.checkout({
            business: "business",
            body: {
                payment_intent_id: "payment_intent_id",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("checkout (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.checkout({
                business: "business",
                body: {
                    payment_intent_id: "payment_intent_id",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("checkout (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.checkout({
                business: "business",
                body: {
                    payment_intent_id: "payment_intent_id",
                },
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("checkout (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.checkout({
                business: "business",
                body: {
                    payment_intent_id: "payment_intent_id",
                },
            });
        }).rejects.toThrow(FiveOneEat.ConflictError);
    });

    test("checkout (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.checkout({
                business: "business",
                body: {
                    payment_intent_id: "payment_intent_id",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("setFulfillment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fulfillment_method: "ship" };
        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .put("/customer/businesses/business/cart/fulfillment")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.setFulfillment({
            business: "business",
            fulfillment_method: "ship",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("setFulfillment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fulfillment_method: "ship" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/businesses/business/cart/fulfillment")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.setFulfillment({
                business: "business",
                fulfillment_method: "ship",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("setFulfillment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fulfillment_method: "ship" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/businesses/business/cart/fulfillment")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.setFulfillment({
                business: "business",
                fulfillment_method: "ship",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("setFulfillment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fulfillment_method: "ship" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/businesses/business/cart/fulfillment")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.setFulfillment({
                business: "business",
                fulfillment_method: "ship",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("setShippingAddress (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            address: { line1: "line1", city: "city", state: "state", postal_code: "postal_code" },
        };
        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .put("/customer/businesses/business/cart/shipping-address")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.setShippingAddress({
            business: "business",
            address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("setShippingAddress (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            address: { line1: "line1", city: "city", state: "state", postal_code: "postal_code" },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/businesses/business/cart/shipping-address")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.setShippingAddress({
                business: "business",
                address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("setShippingAddress (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            address: { line1: "line1", city: "city", state: "state", postal_code: "postal_code" },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/businesses/business/cart/shipping-address")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.setShippingAddress({
                business: "business",
                address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                },
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("setShippingAddress (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            address: { line1: "line1", city: "city", state: "state", postal_code: "postal_code" },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/businesses/business/cart/shipping-address")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.setShippingAddress({
                business: "business",
                address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("listShippingOptions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            options: [
                {
                    provider_rate_id: "provider_rate_id",
                    carrier: "carrier",
                    service: "service",
                    amount: 1.1,
                    amount_cents: 1,
                    currency: "currency",
                    carrier_delivery_days: 1,
                    estimated_delivery_date: "estimated_delivery_date",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/customer/businesses/business/cart/shipping-options")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.listShippingOptions({
            business: "business",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listShippingOptions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/business/cart/shipping-options")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.listShippingOptions({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("listShippingOptions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/business/cart/shipping-options")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.listShippingOptions({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("listShippingOptions (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/business/cart/shipping-options")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.listShippingOptions({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("selectShippingOption (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { provider_rate_id: "provider_rate_id" };
        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/shipping-option")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.selectShippingOption({
            business: "business",
            provider_rate_id: "provider_rate_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("selectShippingOption (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { provider_rate_id: "provider_rate_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/shipping-option")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.selectShippingOption({
                business: "business",
                provider_rate_id: "provider_rate_id",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("selectShippingOption (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { provider_rate_id: "provider_rate_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/shipping-option")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.selectShippingOption({
                business: "business",
                provider_rate_id: "provider_rate_id",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("selectShippingOption (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { provider_rate_id: "provider_rate_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/business/cart/shipping-option")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.selectShippingOption({
                business: "business",
                provider_rate_id: "provider_rate_id",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
