// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("StandsClient", () => {
    test("scan (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                stand: {
                    id: "id",
                    name: "name",
                    address: "address",
                    city: "city",
                    state: "state",
                    latitude: "latitude",
                    longitude: "longitude",
                    notes: "notes",
                },
                business: { id: "id", handle: "handle", name: "name", accepts_payments: true },
                products: [
                    {
                        id: "id",
                        name: "name",
                        slug: "slug",
                        description: null,
                        is_active: true,
                        published_at: null,
                        metadata: null,
                        product_category_id: null,
                        created_at: null,
                        updated_at: null,
                    },
                ],
            },
        };

        server.mockEndpoint().get("/stand/stand").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.stands.scan({
            stand: "stand",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("scan (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/stand/stand").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.stands.scan({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("nearby (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    name: "name",
                    city: "city",
                    latitude: 1.1,
                    longitude: 1.1,
                    distance_meters: 1,
                    is_here: true,
                    business: { id: "id", name: "name", handle: "handle" },
                },
            ],
            meta: { arrival_radius_meters: 1 },
        };

        server
            .mockEndpoint()
            .get("/customer/stands/nearby")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.stands.nearby({
            latitude: 1.1,
            longitude: 1.1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("nearby (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/stands/nearby")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.nearby({
                latitude: 90,
                longitude: 180,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("getCart (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/customer/stands/stand/cart")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.stands.getCart({
            stand: "stand",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getCart (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/stands/stand/cart")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.getCart({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("getCart (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/stands/stand/cart")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.getCart({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("addCartItem (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { variant_id: "variant_id", quantity: 1 };
        const rawResponseBody = {
            data: {
                id: "id",
                items: [
                    {
                        id: "id",
                        variant_id: null,
                        variant_name: null,
                        product_name: null,
                        quantity: 1,
                        unit_price_cents: 1,
                        total_cents: 1,
                        available: true,
                    },
                ],
                subtotal_cents: 1,
                subtotal: 1.1,
                item_count: 1,
                fulfillment: {
                    offered_methods: ["offered_methods"],
                    method: "method",
                    shipping_address: {
                        line1: "line1",
                        line2: null,
                        city: "city",
                        state: "state",
                        postal_code: "postal_code",
                        country: "country",
                    },
                    requires_rate_selection: true,
                    selected_shipping_rate_id: "selected_shipping_rate_id",
                    selected_shipping_amount_cents: 1,
                    checkout_blocker: "checkout_blocker",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.stands.addCartItem({
            stand: "stand",
            body: {
                variant_id: "variant_id",
                quantity: 1,
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addCartItem (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { variant_id: "variant_id", quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.addCartItem({
                stand: "stand",
                body: {
                    variant_id: "variant_id",
                    quantity: 1,
                },
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("addCartItem (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { variant_id: "variant_id", quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.addCartItem({
                stand: "stand",
                body: {
                    variant_id: "variant_id",
                    quantity: 1,
                },
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("addCartItem (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { variant_id: "variant_id", quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.addCartItem({
                stand: "stand",
                body: {
                    variant_id: "variant_id",
                    quantity: 1,
                },
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("clearCart (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/customer/stands/stand/cart").respondWith().statusCode(200).build();

        const response = await client.customer.stands.clearCart({
            stand: "stand",
        });
        expect(response).toEqual(undefined);
    });

    test("clearCart (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/stands/stand/cart")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.clearCart({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("clearCart (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/stands/stand/cart")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.clearCart({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("createPaymentIntent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            client_secret: "client_secret",
            payment_intent_id: "payment_intent_id",
            subtotal: 1.1,
            tax_amount: 1.1,
            platform_fee: 1.1,
            total_amount: 1.1,
            amount: 1,
            currency: "usd",
        };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/payment-intent")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.stands.createPaymentIntent({
            stand: "stand",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createPaymentIntent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/payment-intent")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.createPaymentIntent({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("createPaymentIntent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/payment-intent")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.createPaymentIntent({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("createPaymentIntent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/payment-intent")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.createPaymentIntent({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.ConflictError);
    });

    test("createPaymentIntent (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/payment-intent")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.createPaymentIntent({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("checkout (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = {
            data: {
                id: "id",
                order_number: "order_number",
                status: "status",
                fulfillment_status: "fulfillment_status",
                fulfillment_method: "fulfillment_method",
                pickup_date: "pickup_date",
                pickup_time: "pickup_time",
                subtotal_cents: 1,
                discount_cents: 1,
                shipping_cents: 1,
                tax_cents: 1,
                platform_fee_cents: 1,
                total_cents: 1,
                currency: "currency",
                shipping_address: { key: "value" },
                notes: "notes",
                fulfilled_at: "fulfilled_at",
                refunded_at: "refunded_at",
                business: { id: "id", handle: "handle", name: "name" },
                transaction: {
                    ulid: "ulid",
                    status: "status",
                    refunded_amount_cents: 1,
                    refundable_amount_cents: 1,
                    payment_completed_at: "payment_completed_at",
                    refunded_at: "refunded_at",
                },
                tracking_number: "tracking_number",
                tracking_url: "tracking_url",
                shipments: "shipments",
                items: [{ id: "id", variant_id: "variant_id", quantity: 1, unit_price_cents: 1, total_cents: 1 }],
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.stands.checkout({
            stand: "stand",
            body: {
                payment_intent_id: "payment_intent_id",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("checkout (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.checkout({
                stand: "stand",
                body: {
                    payment_intent_id: "payment_intent_id",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("checkout (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.checkout({
                stand: "stand",
                body: {
                    payment_intent_id: "payment_intent_id",
                },
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("checkout (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.checkout({
                stand: "stand",
                body: {
                    payment_intent_id: "payment_intent_id",
                },
            });
        }).rejects.toThrow(FiveOneEat.ConflictError);
    });

    test("checkout (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { payment_intent_id: "payment_intent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/stands/stand/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.stands.checkout({
                stand: "stand",
                body: {
                    payment_intent_id: "payment_intent_id",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
