// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as FiveOneEat from "../../../../../index.js";

export declare namespace CartClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CartClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CartClient.Options>;

    constructor(options: CartClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {FiveOneEat.customer.GetCartRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     *
     * @example
     *     await client.customer.cart.get({
     *         business: "business"
     *     })
     */
    public get(
        request: FiveOneEat.customer.GetCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.GetCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: FiveOneEat.customer.GetCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.GetCartResponse>> {
        const { business } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as FiveOneEat.customer.GetCartResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/customer/businesses/{business}/cart",
        );
    }

    /**
     * @param {FiveOneEat.customer.AddItemCartRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.addItem({
     *         business: "business",
     *         variant_id: "variant_id",
     *         quantity: 1
     *     })
     */
    public addItem(
        request: FiveOneEat.customer.AddItemCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.AddItemCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__addItem(request, requestOptions));
    }

    private async __addItem(
        request: FiveOneEat.customer.AddItemCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.AddItemCartResponse>> {
        const { business, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.AddItemCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/customer/businesses/{business}/cart",
        );
    }

    /**
     * @param {FiveOneEat.customer.ClearCartRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     *
     * @example
     *     await client.customer.cart.clear({
     *         business: "business"
     *     })
     */
    public clear(
        request: FiveOneEat.customer.ClearCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__clear(request, requestOptions));
    }

    private async __clear(
        request: FiveOneEat.customer.ClearCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { business } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/customer/businesses/{business}/cart",
        );
    }

    /**
     * @param {FiveOneEat.customer.UpdateItemCartRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.ForbiddenError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.updateItem({
     *         cartItem: "cartItem",
     *         quantity: 1
     *     })
     */
    public updateItem(
        request: FiveOneEat.customer.UpdateItemCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.UpdateItemCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateItem(request, requestOptions));
    }

    private async __updateItem(
        request: FiveOneEat.customer.UpdateItemCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.UpdateItemCartResponse>> {
        const { cartItem, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/cart/items/${core.url.encodePathParam(cartItem)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.UpdateItemCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new FiveOneEat.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/customer/cart/items/{cartItem}",
        );
    }

    /**
     * @param {FiveOneEat.customer.RemoveItemCartRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.ForbiddenError}
     * @throws {@link FiveOneEat.NotFoundError}
     *
     * @example
     *     await client.customer.cart.removeItem({
     *         cartItem: "cartItem"
     *     })
     */
    public removeItem(
        request: FiveOneEat.customer.RemoveItemCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.RemoveItemCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__removeItem(request, requestOptions));
    }

    private async __removeItem(
        request: FiveOneEat.customer.RemoveItemCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.RemoveItemCartResponse>> {
        const { cartItem } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/cart/items/${core.url.encodePathParam(cartItem)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.RemoveItemCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new FiveOneEat.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/customer/cart/items/{cartItem}",
        );
    }

    /**
     * Refused with a 422 and a message while the order can't be priced yet: no
     * fulfillment method chosen (when the shop offers several), a shipped order
     * with no shipping address, or calculated shipping with no option chosen.
     * The message is also in the cart's `fulfillment.checkout_blocker`.
     *
     * A 409 `{status: "paid", message, payment_intent_id}` means the cart's
     * payment already went through (never a second payment): finish checkout
     * with that id. A 409 with only a message means it is still processing.
     *
     * @param {FiveOneEat.customer.CreatePaymentIntentCartRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.ConflictError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.createPaymentIntent({
     *         business: "business"
     *     })
     */
    public createPaymentIntent(
        request: FiveOneEat.customer.CreatePaymentIntentCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.CreatePaymentIntentCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createPaymentIntent(request, requestOptions));
    }

    private async __createPaymentIntent(
        request: FiveOneEat.customer.CreatePaymentIntentCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.CreatePaymentIntentCartResponse>> {
        const { business } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart/payment-intent`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.CreatePaymentIntentCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new FiveOneEat.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/customer/businesses/{business}/cart/payment-intent",
        );
    }

    /**
     * Call immediately before presenting or confirming the payment sheet. The
     * cart may have changed since its payment intent was created (another
     * device, a changed address or shipping option), so it is re-priced and
     * the intent brought up to date. Send `amount`, the total in cents the
     * buyer is looking at.
     *
     * - `total_changed: false` — pay with the returned `client_secret`.
     * - `total_changed: true` — show "Your total changed to $X", re-initialise
     *   the payment sheet with the returned `client_secret` (it carries the new
     *   amount), and let the buyer confirm again.
     * - 422 with a message — the order can't be priced yet (the same message
     *   as `fulfillment.checkout_blocker`); the old intent is cancelled.
     * - 409 `status: paid` with `payment_intent_id` — the payment already went
     *   through; call checkout with that id instead.
     * - 409 `status: processing` — the payment is still processing; don't pay
     *   again, check back later.
     *
     * @param {FiveOneEat.customer.RefreshCartPaymentRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.ConflictError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.refreshPaymentIntent({
     *         business: "business",
     *         amount: 1
     *     })
     */
    public refreshPaymentIntent(
        request: FiveOneEat.customer.RefreshCartPaymentRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.RefreshPaymentIntentCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__refreshPaymentIntent(request, requestOptions));
    }

    private async __refreshPaymentIntent(
        request: FiveOneEat.customer.RefreshCartPaymentRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.RefreshPaymentIntentCartResponse>> {
        const { business, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart/payment-intent/refresh`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.RefreshPaymentIntentCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new FiveOneEat.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/customer/businesses/{business}/cart/payment-intent/refresh",
        );
    }

    /**
     * Not gated on commerce readiness: the customer has already paid, so a
     * lapsed readiness check must not stop the order from being recorded.
     * A 409 means the cart changed after the payment was priced: the payment
     * was refunded in full and no order was placed — re-check and pay again.
     *
     * @param {FiveOneEat.customer.CheckoutCartRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.ConflictError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.checkout({
     *         business: "business",
     *         body: {
     *             payment_intent_id: "payment_intent_id"
     *         }
     *     })
     */
    public checkout(
        request: FiveOneEat.customer.CheckoutCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.CheckoutCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__checkout(request, requestOptions));
    }

    private async __checkout(
        request: FiveOneEat.customer.CheckoutCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.CheckoutCartResponse>> {
        const { business, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart/checkout`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.CheckoutCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new FiveOneEat.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/customer/businesses/{business}/cart/checkout",
        );
    }

    /**
     * Switching away from shipping clears the saved shipping address and option.
     *
     * @param {FiveOneEat.customer.ChooseFulfillmentMethodRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.setFulfillment({
     *         business: "business",
     *         fulfillment_method: "ship"
     *     })
     */
    public setFulfillment(
        request: FiveOneEat.customer.ChooseFulfillmentMethodRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.SetFulfillmentCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__setFulfillment(request, requestOptions));
    }

    private async __setFulfillment(
        request: FiveOneEat.customer.ChooseFulfillmentMethodRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.SetFulfillmentCartResponse>> {
        const { business, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart/fulfillment`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.SetFulfillmentCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/customer/businesses/{business}/cart/fulfillment",
        );
    }

    /**
     * Sales tax on a shipped order is worked out from this address. Saving a
     * different address clears the chosen shipping option.
     *
     * @param {FiveOneEat.customer.ShippingAddressRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.setShippingAddress({
     *         business: "business",
     *         address: {
     *             line1: "line1",
     *             city: "city",
     *             state: "state",
     *             postal_code: "postal_code"
     *         }
     *     })
     */
    public setShippingAddress(
        request: FiveOneEat.customer.ShippingAddressRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.SetShippingAddressCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__setShippingAddress(request, requestOptions));
    }

    private async __setShippingAddress(
        request: FiveOneEat.customer.ShippingAddressRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.SetShippingAddressCartResponse>> {
        const { business, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart/shipping-address`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.SetShippingAddressCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/customer/businesses/{business}/cart/shipping-address",
        );
    }

    /**
     * Options are held for 30 minutes; choose one by its `provider_rate_id`.
     *
     * @param {FiveOneEat.customer.ListShippingOptionsCartRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.listShippingOptions({
     *         business: "business"
     *     })
     */
    public listShippingOptions(
        request: FiveOneEat.customer.ListShippingOptionsCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.ListShippingOptionsCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listShippingOptions(request, requestOptions));
    }

    private async __listShippingOptions(
        request: FiveOneEat.customer.ListShippingOptionsCartRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.ListShippingOptionsCartResponse>> {
        const { business } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart/shipping-options`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.ListShippingOptionsCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/customer/businesses/{business}/cart/shipping-options",
        );
    }

    /**
     * Send only the `provider_rate_id` from the shipping options. The price is
     * the one quoted; an option older than 30 minutes is refused with a 422.
     *
     * @param {FiveOneEat.customer.SelectShippingRateRequest} request
     * @param {CartClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FiveOneEat.UnauthorizedError}
     * @throws {@link FiveOneEat.NotFoundError}
     * @throws {@link FiveOneEat.UnprocessableEntityError}
     *
     * @example
     *     await client.customer.cart.selectShippingOption({
     *         business: "business",
     *         provider_rate_id: "provider_rate_id"
     *     })
     */
    public selectShippingOption(
        request: FiveOneEat.customer.SelectShippingRateRequest,
        requestOptions?: CartClient.RequestOptions,
    ): core.HttpResponsePromise<FiveOneEat.customer.SelectShippingOptionCartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__selectShippingOption(request, requestOptions));
    }

    private async __selectShippingOption(
        request: FiveOneEat.customer.SelectShippingRateRequest,
        requestOptions?: CartClient.RequestOptions,
    ): Promise<core.WithRawResponse<FiveOneEat.customer.SelectShippingOptionCartResponse>> {
        const { business, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FiveOneEatEnvironment.Production,
                `customer/businesses/${core.url.encodePathParam(business)}/cart/shipping-option`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FiveOneEat.customer.SelectShippingOptionCartResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new FiveOneEat.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new FiveOneEat.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new FiveOneEat.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FiveOneEatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/customer/businesses/{business}/cart/shipping-option",
        );
    }
}
