// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../../../index.js";

/**
 * @example
 *     {
 *         stand: "stand",
 *         body: {
 *             variant_id: "variant_id",
 *             quantity: 1
 *         }
 *     }
 */
export interface AddCartItemStandsRequest {
    /** The stand ID */
    stand: string;
    body: FiveOneEat.AddCartItemRequest;
}
