// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         stand: "stand"
 *     }
 */
export interface ClearCartStandsRequest {
    /** The stand ID */
    stand: string;
}
