// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         latitude: 1.1,
 *         longitude: 1.1
 *     }
 */
export interface NearbyStandsRequest {
    /** The device's latitude. @example 42.6526 */
    latitude: number;
    /** The device's longitude. @example -73.7562 */
    longitude: number;
}
