// This file was auto-generated by Fern from our API Definition.

/**
 * A variant to add to a storefront or stand cart. It must be one the shop or
 * stand sells: its product active, published and on sale there, with a price
 * there. Anything else is refused on `variant_id`.
 */
export interface AddCartItemRequest {
    variant_id: string;
    quantity: number;
}
