// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface BusinessEvent {
    id: string;
    business_id: string;
    title: string;
    description: string;
    starts_at: string;
    ends_at: string;
    location: string;
    venue_address: string;
    venue_city: string;
    venue_state: string;
    venue_zipcode: string;
    venue_country: string;
    latitude: number | null;
    longitude: number | null;
    is_all_day: string;
    is_featured: string;
    ticket_sales_enabled: string;
    is_published: string;
    published_at: string;
    sort_order: string;
    image?: (string | null) | undefined;
    /** The event's ticket tiers. */
    ticket_types?: FiveOneEat.BusinessEventTicketType[] | undefined;
    rsvps_count?: number | undefined;
    attendees_count?: number | undefined;
    tickets_count?: number | undefined;
    created_at: string;
    updated_at: string;
}
