// This file was auto-generated by Fern from our API Definition.

export interface CartResource {
    id: string;
    items: CartResource.Items.Item[];
    subtotal_cents: number;
    subtotal: number;
    item_count: number;
    /** How the order will be fulfilled and what checkout still needs. */
    fulfillment: CartResource.Fulfillment;
}

export namespace CartResource {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            variant_id: string | null;
            variant_name: string | null;
            product_name: string | null;
            quantity: number;
            unit_price_cents: number;
            total_cents: number;
        }
    }

    /**
     * How the order will be fulfilled and what checkout still needs.
     */
    export interface Fulfillment {
        offered_methods: string[];
        method: string | null;
        shipping_address: Fulfillment.ShippingAddress | null;
        requires_rate_selection: boolean;
        selected_shipping_rate_id: string | null;
        selected_shipping_amount_cents: number | null;
        checkout_blocker: string | null;
    }

    export namespace Fulfillment {
        export interface ShippingAddress {
            line1: string;
            line2: string | null;
            city: string;
            state: string;
            postal_code: string;
            country: string;
        }
    }
}
