// This file was auto-generated by Fern from our API Definition.

export interface ConflictErrorBody {
    status: ConflictErrorBody.Status;
    message: ConflictErrorBody.Message;
    payment_intent_id: string;
}

export namespace ConflictErrorBody {
    export const Status = {
        Paid: "paid",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Message = {
        YouveAlreadyPaidForTheseTicketsTheyllArriveByEmailShortly:
            "You've already paid for these tickets \u2014 they'll arrive by email shortly.",
    } as const;
    export type Message = (typeof Message)[keyof typeof Message];
}
