// This file was auto-generated by Fern from our API Definition.

export interface ExploreStand {
    id: string;
    name: string;
    address: string | null;
    city: string | null;
    state: string | null;
    latitude: number;
    longitude: number;
    business?: ExploreStand.Business | undefined;
}

export namespace ExploreStand {
    export interface Business {
        id: string;
        name: string;
        handle: string;
        logo: string | null;
    }
}
