// This file was auto-generated by Fern from our API Definition.

export const FulfillmentType = {
    Ship: "ship",
    Pickup: "pickup",
    InPerson: "in_person",
} as const;
export type FulfillmentType = (typeof FulfillmentType)[keyof typeof FulfillmentType];
