// This file was auto-generated by Fern from our API Definition.

export interface NearbyStand {
    id: string;
    name: string;
    city: string | null;
    latitude: number;
    longitude: number;
    /** Straight-line distance from the coordinates sent, in meters. */
    distance_meters: number;
    /** Within the arrival radius: the customer is at this stand. */
    is_here: boolean;
    business: NearbyStand.Business;
}

export namespace NearbyStand {
    export interface Business {
        id: string;
        name: string;
        handle: string;
    }
}
