// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface OrderResource {
    id: string;
    order_number: string;
    status: string;
    fulfillment_status: string;
    fulfillment_method: string;
    /** The buyer's pickup day (Y-m-d) for a pickup order, when they chose one. */
    pickup_date: string | null;
    /** The buyer's pickup time (H:i) for a pickup order, when they chose one. */
    pickup_time: string | null;
    subtotal_cents: number;
    discount_cents: number;
    shipping_cents: number;
    tax_cents: number;
    platform_fee_cents: number;
    total_cents: number;
    currency: string;
    shipping_address: Record<string, unknown> | null;
    notes: string;
    fulfilled_at: string;
    refunded_at: string;
    business?: OrderResource.Business | undefined;
    transaction?: (OrderResource.Transaction | null) | undefined;
    tracking_number?: (string | null) | undefined;
    tracking_url?: (string | null) | undefined;
    shipments: OrderResource.Shipments;
    items?: FiveOneEat.OrderItemResource[] | undefined;
    created_at: string;
    updated_at: string;
}

export namespace OrderResource {
    export interface Business {
        id: string;
        handle: string;
        name: string;
    }

    export interface Transaction {
        ulid: string;
        status: string;
        refunded_amount_cents: number;
        /**
         * What a refund can still return: the total less what's refunded and
         * the customer-paid service fee and its tax, which are never refunded.
         */
        refundable_amount_cents: number;
        payment_completed_at: string;
        refunded_at: string;
    }

    export type Shipments = string | string[];
}
