// This file was auto-generated by Fern from our API Definition.

export interface ProductResource {
    id: string;
    name: string;
    slug: string;
    description: string | null;
    is_active: boolean;
    published_at: string | null;
    metadata: Record<string, unknown> | null;
    product_category_id: string | null;
    /**
     * Owner-only: shared with the customer stand shop, so it appears only
     * when the business controller loaded the `taxCode` relation.
     */
    tax_code?: (string | null) | undefined;
    category?: unknown[] | undefined;
    images?: unknown[] | undefined;
    variants?: unknown[] | undefined;
    default_variant?: unknown[] | undefined;
    created_at: string | null;
    updated_at: string | null;
}
