// This file was auto-generated by Fern from our API Definition.

export interface TaxCode {
    id: string;
    name: string;
    description: string | null;
    category: TaxCode.Category;
    /** Whether a product may use this code. */
    allowed_on_products: boolean;
    /** Whether an event ticket type may use this code. */
    allowed_on_ticket_types: boolean;
}

export namespace TaxCode {
    export const Category = {
        Food: "food",
        Goods: "goods",
        Services: "services",
        Digital: "digital",
        Admissions: "admissions",
        Other: "other",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
