// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface TicketOrder {
    id: string;
    order_number: string;
    event?: TicketOrder.Event | undefined;
    transaction?: FiveOneEat.Transaction | undefined;
    tickets?: FiveOneEat.Ticket[] | undefined;
}

export namespace TicketOrder {
    export interface Event {
        id: string;
        title: string;
        starts_at: string;
        ends_at: string;
        location: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipcode: string | null;
        latitude: number | null;
        longitude: number | null;
        business: Event.Business | null;
    }

    export namespace Event {
        export interface Business {
            id: string;
            name: string;
            handle: string;
        }
    }
}
