// This file was auto-generated by Fern from our API Definition.

export interface ListShippingOptionsCartResponse {
    options: ListShippingOptionsCartResponse.Options.Item[];
}

export namespace ListShippingOptionsCartResponse {
    export type Options = Options.Item[];

    export namespace Options {
        export interface Item {
            provider_rate_id: string;
            carrier: string;
            service: string;
            amount: number;
            amount_cents: number;
            currency: string;
            carrier_delivery_days: number | null;
            estimated_delivery_date: string | null;
        }
    }
}
