// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         order: "order",
 *         carrier: "carrier",
 *         tracking_number: "tracking_number"
 *     }
 */
export interface AddTrackingProductOrdersRequest {
    /** The order ID */
    order: string;
    carrier: string;
    tracking_number: string;
    tracking_url?: string | null;
    service?: string | null;
}
