// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         order: "order"
 *     }
 */
export interface GetLabelRatesProductOrdersRequest {
    /** The order ID */
    order: string;
}
