// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         order: "order",
 *         provider_rate_id: "provider_rate_id"
 *     }
 */
export interface PurchaseLabelProductOrdersRequest {
    /** The order ID */
    order: string;
    provider_rate_id: string;
}
