// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         order: "order"
 *     }
 */
export interface RefundOrderRequest {
    /** The order ID */
    order: string;
    /** Optional, 1–255 characters. A retry with the same key returns the refund already made instead of refunding again. */
    "Idempotency-Key"?: string;
    amount?: number | null;
    reason?: string | null;
}
